Adding weather events
customrealms/core pull request #14
Opened 2021-11-25 17:55 UTC by Daniel-Glz

2021-11-25 18:45 UTC, connerdouglass commented
Other than my one small comment, I think this looks great. Maybe @AL1L can review it also and then we'll merge

2021-11-25 19:50 UTC, AL1L requested changes

2021-11-25 19:50 UTC, AL1L commented on src/events/types/weather/LightningStrikeEvent.ts
> +    public getLightning():LightningStrike {
You can just return an Entity for now. 

Although as the Entity type has only one extra method, I'd prefer you go ahead and make the Entity class, don't have to though.

2021-11-25 19:50 UTC, AL1L commented on src/events/types/weather/LightningStrikeEventCause.ts
> +    COMMAND = 'COMMAND',
This file needs documentation

2021-11-25 19:50 UTC, AL1L commented on src/events/types/weather/LightningStrikeEvent.ts
> +    * Gets the cause of this lightning strike
Almost all of your method documentation is missing one space, the `*`s should all line up. I guess it's not that important, but would be nice to fix if you have the time

2021-11-25 19:50 UTC, AL1L commented on src/events/types/weather/LightningStrikeEvent.ts
> +    public getCause():LightningStrikeEventCause {
Missing a space before the return type.

@connerdouglass I was thinking, we should add eslint and prettier

2021-11-25 19:50 UTC, AL1L commented on src/events/types/weather/LightningStrikeEvent.ts
> +        return this.toJava().getCause();
This should have `.getNane()` to get the enum name.

2021-11-27 02:18 UTC, connerdouglass commented
Today I made some changes on `master` to the entity classes. Please merge your branch with the latest changes on master, and use the `LightningStrike` entity I added there, instead of yours. Thanks!

2021-11-27 06:20 UTC, Daniel-Glz commented
> Today I made some changes on `master` to the entity classes. Please merge your branch with the latest changes on master, and use the `LightningStrike` entity I added there, instead of yours. Thanks!

Ready, my branch is up to date with the latest changes.

2021-11-27 16:12 UTC, merged